### ISSUE TITLE
Animation format

### ISSUE THREAD

**Issue by Cj-bc** [Cj-bc/asciiart-hs#2]
# what to suggest

Create format to represent animation

```yaml
title: hoge
# 'type' represents which AA can use this animation
#   'humanoid': all 'humanoid' AAs can use this.
#   'singleton': AA with only one file can use this.
#   'other': AA that is constructed by group of AAs.
type: [humanoid|singleton|other]
data:
  - timestamp: 0
     ...
```

```yaml
# example for singleton
title: hoge
type: singleton
data:
  - timestamp: 0 # frame number
     # 'translate' translates the AA by given amount.
     # e.g. if AA is now (20, 30), it'll move to (30, 10)
     translate:
       x: 10
       y: -20
     # 'rotate' rotates the AA by given amount.
     # e.g. if AA's rotation is 30 degree,  it'll rotate to 90 degree.
     rotate: 60
  - timestamp: 10
     # 'translateTo' sets AA's position to given value.
     # e.g. Wherever AA is placed, it'll be move to (0, 0)
     translateTo:
       x: 0
       y: 0
     # 'rotateTo' sets AA's rotation to given value.
     # i.e. However AA is rotated, it'll be reset to 0
     rotateTo: 0
```

# Problem here

I'm wondering if it's better to make other library for the animation instead of adding here.

**Comment by Cj-bc** [comment]
example for model, humanoid
(not animation, but related

```yaml
title: 
type: humanoid
author: Cj-bc
copyright: 
data:
  head:
    eye_right: parts/face/eye_right.yaml
    eye_left:
      default: parts/face/eye_left.yaml
      emotes:
        - name: sad
          path: parts/face/emote2/eye_left.yaml
    nose: parts/face/nose.yaml
    mouth: parts/face/mouth.yaml
```
